### ISSUE TITLE
Lab -04: wrong code for Colab in visualization

### ISSUE THREAD

**Issue by foresterhema** [stephenbaek/bigdata#4]
@stephenbaek Hi Steve, I am running the lab materials for Tuesday class. When you visualize the MDS, there are all errors:

For example:

Your code: 

projected_mds.plot(kind='scatter', x='MDS1', y='MDS2', color=data.absences, colormap='cool')

Note: You did not define the term data and it does not has the attribute "absences"

The correct answer: 

projected_mds.plot(kind='scatter', x='MDS1', y='MDS2',color=df.absences_discretized, colormap='cool')

All MDS visualization related codes are having this issue. Please correct it. Thanks.

Yusen

**Comment by stephenbaek** [comment]
You picked up an issue on still on-going work. Btw, please push edits directly on your branch next time and send a merge request. For the minor things like this, you don't need to open an issue.
